apiVersion: v1
kind: Service
metadata:
  name: dotnet-vault-example
spec:
  type: NodePort
  selector:
    app: dotnet-vault-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008